package lk.ijse.salon.util;

/*
    @author THINUX
    @created 15-Nov-22
*/

public enum Routes {
    LOGIN, ADMIN_MENU, RECEPTION_MENU, MANAGE_CUSTOMER, MANAGE_APPOINTMENT, MANAGE_EMPLOYEES, MANAGE_SUPPLIERS,
    MANAGE_SERVICES, MANAGE_CUSTOMER_ORDERS, MANAGE_PRODUCT, REPORT, DAILY_REPORT, MONTHLY_REPORT,
    ANNUAL_REPORT, MANAGE_SALARY, MANAGE_PAYMENT, MANAGE_SUPPLIERS_ORDERS, DASHBOARD, GIVEN_SERVICE

}
